version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pepito@pepito.com"
      PGADMIN_DEFAULT_PASSWORD: "pepito"
    ports:
      - "80:80"
    depends_on:
      - postgres


  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

    depends_on:
      - pgadmin